import {
  BarChart2, Scale, RefreshCw, Activity, TrendingUp,
  Calendar, Zap, Heart, Target, Dumbbell, User,
  Flame, Trophy, Droplets, Layers, Users, Video, Brain, Shield
} from 'lucide-react'

export const WIDGET_REGISTRY = [
  {
    id: 'calorie_ring',
    label: 'Calories & Macro Ring',
    subtitle: 'Daily target donut ring and macro breakdown',
    Icon: Flame,
    pages: ['dashboard'],
  },
  {
    id: 'readiness_score',
    label: 'Daily Readiness Dial',
    subtitle: 'Recovery and neuromuscular readiness score',
    Icon: Zap,
    pages: ['dashboard', 'progress'],
  },
  {
    id: 'pr_trophy',
    label: 'PR Trophy Shelf',
    subtitle: 'Estimated 1RM records & milestone badges',
    Icon: Trophy,
    pages: ['dashboard', 'progress'],
  },
  {
    id: 'hydration_quick',
    label: '1-Tap Hydration Tracker',
    subtitle: 'Quick +250ml / +500ml water progress meter',
    Icon: Droplets,
    pages: ['dashboard'],
  },
  {
    id: 'weekly_adherence',
    label: 'Weekly Adherence',
    subtitle: '7-day target workout completion tracker',
    Icon: Calendar,
    pages: ['dashboard'],
  },
  {
    id: 'muscle_recovery',
    label: 'Muscle Recovery Status',
    subtitle: 'Estimated recovery levels by muscle group',
    Icon: Layers,
    pages: ['dashboard', 'progress'],
  },
  // ── Coach-Exclusive Widgets ──
  {
    id: 'coach_roster',
    label: 'Coach Athlete Roster',
    subtitle: 'Active athletes, injury flags, and fatigue status',
    Icon: Users,
    role: 'coach',
    pages: ['dashboard'],
  },
  {
    id: 'coach_schedule',
    label: "Today's Coaching Schedule",
    subtitle: 'Upcoming 1-on-1 consultations and video calls',
    Icon: Video,
    role: 'coach',
    pages: ['dashboard'],
  },
  {
    id: 'coach_anomalies',
    label: 'Athlete AI Anomaly Detector',
    subtitle: 'Automated fatigue spikes and injury risk alerts',
    Icon: Brain,
    role: 'coach',
    pages: ['dashboard'],
  },
  // ── Standard Widgets ──
  {
    id: 'workouts_per_week',
    label: 'Workouts per week',
    subtitle: 'Track your completed workouts each week',
    Icon: Calendar,
    pages: ['dashboard', 'progress'],
  },
  {
    id: 'body_map',
    label: 'Body Map',
    subtitle: 'Anatomical muscle group & injury heatmap',
    Icon: User,
    pages: ['dashboard', 'progress'],
  },
  {
    id: 'weight_over_time',
    label: 'Weight over time',
    subtitle: 'Track your bodyweight progression',
    Icon: Scale,
    pages: ['dashboard', 'progress'],
  },
  {
    id: 'reps_over_time',
    label: 'Reps over time',
    subtitle: 'Track your rep count per exercise',
    Icon: RefreshCw,
    pages: ['dashboard', 'progress'],
  },
  {
    id: 'weight_reps_combined',
    label: 'Weight & Reps',
    subtitle: 'Visualize weight and reps together over time',
    Icon: BarChart2,
    pages: ['dashboard', 'progress'],
  },
  {
    id: 'volume_progression',
    label: 'Volume Progression',
    subtitle: 'Session load over time',
    Icon: TrendingUp,
    pages: ['dashboard'],
  },
  {
    id: 'weekly_volume',
    label: 'Weekly Volume',
    subtitle: 'This week vs last week comparison',
    Icon: Activity,
    pages: ['dashboard'],
  },
  {
    id: 'training_split',
    label: 'Training Split',
    subtitle: 'Muscle group distribution donut chart',
    Icon: Target,
    pages: ['dashboard'],
  },
  {
    id: 'activity_map',
    label: 'Activity Map',
    subtitle: 'Workout intensity calendar heatmap',
    Icon: Calendar,
    pages: ['dashboard', 'progress'],
  },
  {
    id: 'streak_tracker',
    label: 'Streak Tracker',
    subtitle: 'Current and best training streak',
    Icon: Zap,
    pages: ['dashboard'],
  },
  {
    id: 'fatigue_history',
    label: 'Fatigue History',
    subtitle: 'Recent fatigue check results',
    Icon: Heart,
    pages: ['dashboard', 'progress'],
  },
  {
    id: 'exercise_tracker',
    label: 'Exercise Tracker',
    subtitle: 'Track a specific exercise over time',
    Icon: Dumbbell,
    pages: ['dashboard', 'progress'],
  },
  {
    id: 'sleep_tracker',
    label: 'Sleep Tracker',
    subtitle: 'Correlate sleep with workout volume',
    Icon: Zap,
    pages: ['dashboard', 'progress'],
  },
]

export const METRIC_LABELS = {
  est_1rm:      'Best set (est. 1RM)',
  max_weight:   'Best set (max weight)',
  total_volume: 'Total volume',
  best_reps:    'Best set (reps)',
}
